openapi: 3.0.0
info:
  version: "1.0.0"
  title: Digital line REST API

# Paths supported by the server application
paths:
  /lines:
    get:
      #operationId: api.lines.search
      summary: "Get an array of lines"
      tags:
        - lines
      responses:
        200:
          description: "A JSON array of lines"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Line'
    post:
      #operationId: api.lines.post
      summary: "Add new line"
      tags:
        - lines
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Line"
      responses:
        201:
          description: "Line successfully added"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Line'
  /lines/{line_id}:
    get:
      tags:
        - lines
      parameters:
        - in: path
          name: line_id
          schema:            
            type: integer
      responses:
        200:
          description: "Ok"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Line"
  /clerks:
    get:
      #operationId: api.clerks.search
      summary: "Get an array of clerks"
      tags:
        - clerks
      responses:
        200:
          description: "A JSON array of clerks"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Clerk'
    post:
      #operationId: api.clerks.post
      summary: "Add new clerk"
      tags:
        - clerks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Clerk"
      responses:
        201:
          description: "Clerk successfully added"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Clerk'
  /clerks/{clerk_id}:
    get:
      tags:
        - clerks
      parameters:
        - in: path
          name: clerk_id
          schema:            
            type: integer
      responses:
        200:
          description: "Ok"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Clerk"
  /clients:
    get:
      #operationId: api.clients.search
      summary: "Get an array of clients"
      tags:
        - clients
      responses:
        200:
          description: "A JSON array of clients"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'
    post:
      #operationId: api.clients.post
      summary: "Add new client"
      tags:
        - clients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Client"
      responses:
        201:
          description: "Client successfully added"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
  /clients/{client_id}:
    get:
      tags:
        - clients
      parameters:
        - in: path
          name: client_id
          schema:            
            type: integer
      responses:
        200:
          description: "Ok"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Client"

  /lines/{line_id}/clients/{client_id}:
    post:
      operationId: api.lines_manipulations.add_client_to_line
      description: "Add client to line"
      tags:
        - lines_manipulations
      parameters:
        - in: path
          name: line_id
          schema:
            type: integer
        - in: path
          name: client_id
          schema:
            type: integer
      responses:
        200:
          description: "Ok"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Line"
  
  /lines/{line_id}/clerks/{clerk_id}:
    post:
      operationId: api.lines_manipulations.add_clerk_to_line
      description: "Add clerk to line"
      tags:
        - lines_manipulations
      parameters:
        - in: path
          name: line_id
          schema:
            type: integer
        - in: path
          name: clerk_id
          schema:
            type: integer
      responses:
        200:
          description: "Ok"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Line"


components:
  schemas:
    Line:
      type: object
      properties:
        line_id:
          type: integer
        name:
          type: string
      required:
        - line_id
        - name
    Clerk:
      type: object
      properties:
        clerk_id:
          type: integer
        name:
          type: string
      required:
        - clerk_id
        - name
    Client:
      type: object
      properties:
        client_id:
          type: integer
        name:
          type: string
      required:
        - client_id
        - name