openapi: 3.0.0
info:
  version: "1.0.0"
  title: Digital line REST API

# Paths supported by the server application
paths:
  /clerks:
    get:
      #operationId: api.clerks.search
      summary: "Get an array of clerks"
      responses:
        200:
          description: "A JSON array of clerks"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Clerk'
    post:
      #operationId: api.clerks.post
      summary: "Add new clerk"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Clerk"
      responses:
        201:
          description: "Clerk successfully added"

components:
  schemas:
    Clerk:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - id
        - name